stages:
  - unittest
  - ci

cache:
  paths:
    - "~/.cache/pip/"

before_script:
  - "python3 -V && python3 -m django --version"
  - "echo $CI_JOB_ID / $GITLAB_USER_EMAIL"


UnitTest:
  stage: unittest
  script:
    - "python3 ros/MainApplication/AppRootDir/manage.py test --verbosity 2"

    
CoverageTest:
  stage: unittest
  script:
    - "echo 'coverage_test start!'"
    - "python3 -m coverage run --source='.' ./MainApplication/AppRootDir/manage.py test"
    - "coverage report"
 #   - "coverage erase"
    
IntegrationTest:
  stage: ci
  script:
    - "echo 'integration_test start!'"
    #    - "python3 ros/MainApplication/AppRootDir/manage.py check --verbosity 2"
    #    - 
    - "echo 'integration_test end!'"
