stages:
  - unittest
  - ci
  - coverage  

cache:
  paths:
    - "~/.cache/pip/"

before_script:
  - "mysql -u root -p'ece651db' -e \"DROP DATABASE IF EXISTS test_django\""
  - "python3 -V && python3 -m django --version"
  - "echo $CI_JOB_ID / $GITLAB_USER_EMAIL"


LoginTest:
  stage: unittest
  script:
    - "cd ./MainApplication/AppRootDir/"
    - "python3 manage.py test login.tests  --verbosity 2"

ReservationTest:
  stage: unittest
  script:
    - "cd ./MainApplication/AppRootDir/"
    - "python3 manage.py test reservation.tests  --verbosity 2"

WaitlistTest:
  stage: unittest
  script:
    - "cd ./MainApplication/AppRootDir/"
    - "python3 manage.py test waitlist.tests  --verbosity 2"

IntegrationTest:
  stage: ci
  script:
    - "cd ./MainApplication/AppRootDir/"
    - "python3 manage.py test test_integration  --verbosity 2"

CoverageTest:
  stage: coverage
  script:
    - "cd ./MainApplication/AppRootDir/"
    - "python3 -m coverage erase"
    - "python3 -m coverage run --source='.' manage.py test login.tests reservation.tests waitlist.tests"
    - "python3 -m coverage report"
    
