# Generated by Django 3.0.2 on 2020-03-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200202_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='catagory',
            field=models.CharField(default='customer', max_length=64),
        ),
    ]
