# Generated by Django 3.0.2 on 2020-03-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap', models.IntegerField(default=4)),
                ('ocupied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'table',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('rsv_number', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('rsv_time', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Table')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservation',
            },
        ),
    ]
