# Generated by Django 3.0.2 on 2020-03-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='no_of_guests',
            field=models.IntegerField(default=4),
        ),
    ]
