# Generated by Django 3.0.2 on 2020-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_no_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ocupied',
            field=models.CharField(default='Vacant', max_length=64),
        ),
    ]
