# Generated by Django 3.0.2 on 2020-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200324_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='ocupied',
        ),
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
