# Generated by Django 3.0.2 on 2020-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
