# Generated by Django 3.0.2 on 2020-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20200322_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlist',
            old_name='number',
            new_name='id',
        ),
    ]
